# Usar a imagem oficial do SDK do .NET para compilar e publicar a aplicação
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copiar os arquivos do projeto para o contêiner
COPY . .

# Restaurar dependências
RUN dotnet restore

# Compilar e publicar o projeto
RUN dotnet publish -c Release -o out

# Usar a imagem do .NET Runtime para rodar a aplicação
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

# Expor a porta 80 para a API
EXPOSE 80
ENTRYPOINT ["dotnet", "MinhaApi.dll"]
